package:
  name: spscore
  version: "1.0.0"

source:
  git_url: https://github.com/malabz/spscore.git
  # git_rev: v2.0.0

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

  host:
    - zlib

    - sysroot_linux-64 2.17

  run:
    - zlib


test:
  commands:
    - spscore -h


about:
  home: https://github.com/malabz/spscore.git
  license: MIT
  summary: "spscore"
